@startuml
'https://plantuml.com/sequence-diagram
actor User
participant ":Duke" as Duke #LightBlue
participant ":IncomeParser" as IncomeParser #LightGreen
participant ":AddIncomeCommand" as AddIncomeCommand #LightCoral
participant ":IncomeManager" as IncomeManager #LightGoldenRodYellow
autonumber

User -> Duke: "add income <AMOUNT> / <SOURCE>"
activate Duke

Duke -> IncomeParser: IncomeParser.parseAddIncomeCommand();
activate IncomeParser

IncomeParser -> AddIncomeCommand: input AMOUNT, SOURCE
activate AddIncomeCommand

AddIncomeCommand -> IncomeManager: addIncome()
activate IncomeManager
deactivate AddIncomeCommand
deactivate IncomeManager
deactivate IncomeParser
deactivate Duke

@enduml