@startuml
hide footbox

actor User
participant ":Duke" as Duke #LightBlue
participant ":AlertParser" as AlertParser #LightGreen

User -> Duke: "alert set 20"
activate Duke

Duke -> AlertParser: parse("alert set 20",\nfundsAlert)
activate AlertParser

  AlertParser -> AlertParser: validate command format
  activate AlertParser
  AlertParser --> AlertParser
  deactivate AlertParser

create ":AlertCommand" as AlertCommand #LightCoral
AlertParser -> AlertCommand: new AlertCommand (20.0, fundsAlert)
activate AlertCommand
AlertCommand --> AlertParser: return alertCommand
deactivate AlertCommand



participant ":Ui" as Ui #Lavender
participant ":FundsAlert" as FundsAlert #LightGoldenRodYellow

AlertParser --> Duke: return alertCommand
deactivate AlertParser

Duke -> AlertCommand: execute(expenseList, ui)
activate AlertCommand

AlertCommand -> FundsAlert: setWarningThreshold(20.0)
activate FundsAlert

  FundsAlert -> FundsAlert: validate threshold
  activate FundsAlert
  FundsAlert --> FundsAlert
  deactivate FundsAlert

FundsAlert --> AlertCommand
deactivate FundsAlert

AlertCommand -> Ui: showMessage\n("Funds alert threshold\nset to $20.00")
activate Ui
Ui --> User: println("Funds alert threshold set to $20.00");
Ui --> AlertCommand
deactivate Ui

AlertCommand --> Duke
deactivate AlertCommand

Duke --> User: command completed
deactivate Duke
@enduml